package com.qc.electrodeqclab.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.qc.electrodeqclab.model.BatchRelease;
import com.qc.electrodeqclab.model.TestRequest;
import com.qc.electrodeqclab.model.TestResult;
import com.qc.electrodeqclab.repository.BatchReleaseRepository;
import com.qc.electrodeqclab.repository.TestResultRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.time.LocalDateTime;
import java.io.FileOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
@Service
public class PDFGenerationService {

    @Autowired
    private TestResultRepository resultRepository;

    @Autowired
    BatchReleaseRepository releaseRepository;

    @Value("${coa.directory:./coa-reports/}")
    private String coaDirectory;

    public String generateCOA(TestRequest request) throws Exception {
        java.io.File dir = new java.io.File(coaDirectory);
        if(!dir.exists()) {
            dir.mkdirs();
        }

        String filePath = coaDirectory + "COA" + request.getBatchNumber() + ".pdf";
        List<TestResult> results = resultRepository.findByTestRequest(request);

        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        document.open();

        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 10);

        // Title
        Paragraph title = new Paragraph("CERTIFICATE OF ANALYSIS", titleFont);
        title.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(title);
        document.add(Chunk.NEWLINE);

        // Separator line
        Paragraph line = new Paragraph("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        line.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(line);
        document.add(Chunk.NEWLINE);

        // Batch Information
        document.add(new Paragraph("Batch Number: " + request.getBatchNumber(), normalFont));
        document.add(new Paragraph("Electrode Type: " + request.getElectrodeType(), normalFont));
        document.add(new Paragraph("Request Number: " + request.getRequestNumber(), normalFont));
        document.add(new Paragraph("Release Date: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), normalFont));

        document.add(Chunk.NEWLINE);

        // Test Results Table
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{30f, 20f, 20f, 20f});

        PdfPCell cell1 = new PdfPCell(new Phrase("Test Name", headerFont));
        cell1.setPadding(8);
        table.addCell(cell1);

        PdfPCell cell2 = new PdfPCell(new Phrase("Measured Value", headerFont));
        cell2.setPadding(8);
        table.addCell(cell2);

        PdfPCell cell3 = new PdfPCell(new Phrase("Standard Range", headerFont));
        cell3.setPadding(8);
        table.addCell(cell3);

        PdfPCell cell4 = new PdfPCell(new Phrase("Result", headerFont));
        cell4.setPadding(8);
        table.addCell(cell4);

        // Table Data
        for (TestResult result : results) {
            String testName = result.getTestMaster().getTestName();
            String value = result.getMeasuredValue() + " " + result.getTestMaster().getUnit();
            String standard = result.getTestMaster().getMinStandardValue() + " - " +
                    result.getTestMaster().getMaxStandardValue() + " " +
                    result.getTestMaster().getUnit();
            String status = result.getIsPassed() ? "PASS" : "FAIL";

            table.addCell(new Phrase(testName, normalFont));
            table.addCell(new Phrase(value, normalFont));
            table.addCell(new Phrase(standard, normalFont));
            table.addCell(new Phrase(status, normalFont));
        }

        document.add(table);
        document.add(Chunk.NEWLINE);

        // Footer
        Paragraph footer = new Paragraph("This certificate is auto-generated by Electrode QC Lab System",
                FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8));
        footer.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(footer);

        document.close();

        return filePath;
    }
}
